spring:
  application:
    name: eureka-server2

server:
  port: 8002

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8001}/eureka/

